version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}
    redis_data: {}
    mosquitto_data: {}
    docker_gen: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    ports:
      - 9090:9090
    networks:
      - front-tier
      - back-tier
    restart: always

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    # user: "104"
    environment:
      - VIRTUAL_HOST=grafana.supergreenlab.com
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
    restart: always

  supergreenlog:
    image: supergreenlab/supergreenlog
    command:
      - '-mqtt_username=supergreen'
      - '-mqtt_password=multipass'
    depends_on:
      - redis
      - mqtt
    networks:
      - back-tier
    restart: always

  supergreenpromproxy:
    image: supergreenlab/supergreenpromproxy
    environment:
      - VIRTUAL_HOST=metrics.supergreenlab.com
    depends_on:
      - prometheus
    networks:
      - back-tier
    restart: always

  redis:
    image: redis
    volumes:
      - redis_data:/data
    restart: always
    #    ports:
    #      - 6379:6379
    networks:
      - back-tier

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    networks:
      - back-tier
      - front-tier
    volumes:
      - ./mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  update:
    image: nginx
    environment:
      - VIRTUAL_HOST=update.supergreenlab.com
    volumes:
      - ./update:/usr/share/nginx/html
    networks:
      - back-tier

  app:
    image: nginx
    environment:
      - VIRTUAL_HOST=app.supergreenlab.com
    volumes:
      - ./controller:/usr/share/nginx/html
    networks:
      - back-tier

  live:
    image: nginx
    environment:
      - VIRTUAL_HOST=live.supergreenlab.com
    volumes:
      - ./live:/usr/share/nginx/html
    networks:
      - back-tier

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - docker_gen:/etc/nginx/conf.d
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - front-tier
      - back-tier
    depends_on:
      - dockergen
      - grafana
      - app
      - update
      - supergreenpromproxy
      - live
      - dockergen

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - docker_gen:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - front-tier
      - back-tier
    depends_on:
      - grafana
      - app
      - update
      - supergreenpromproxy
      - live
